language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
  - DJANGO=1.4.0 DJANGO_SETTINGS_MODULE="suit.tests.settings"
  - DJANGO=1.4.2 DJANGO_SETTINGS_MODULE="suit.tests.settings"
  - DJANGO=1.4.5 DJANGO_SETTINGS_MODULE="suit.tests.settings"
  - DJANGO=1.5 DJANGO_SETTINGS_MODULE="suit.tests.settings"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test suit
